#!/usr/bin/env python3
"""Offline tests for skills/gameplay-postproduction/scripts/check_postproduction.py.

Everything here is deterministic and needs no model, no network, no credentials and no fixture
media committed to the repo. The only external dependency is `ffmpeg`/`ffprobe`, and only for the
`ready`-mode cases, which build a throwaway MP4 in a temp directory.

Run:  python3 tests/test_check_postproduction.py
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
CHECKER = ROOT / "skills" / "gameplay-postproduction" / "scripts" / "check_postproduction.py"
AUDIT_SCRIPT = ROOT / "skills" / "gameplay-postproduction" / "scripts" / "check_timeline_audit.py"
EXAMPLES = ROOT / "examples"

PASS = 0
FAIL = 0


def run(mode: str, target: Path, *extra: str) -> tuple[int, dict]:
    p = subprocess.run([sys.executable, str(CHECKER), mode, str(target), "--json", *extra],
                       capture_output=True, text=True)
    try:
        payload = json.loads(p.stdout or "{}")
    except json.JSONDecodeError:
        payload = {"_raw": p.stdout, "_stderr": p.stderr}
    return p.returncode, payload


def expect(name: str, want_rc: int, mode: str, target: Path, *extra: str,
           substr: str | None = None) -> dict:
    global PASS, FAIL
    rc, payload = run(mode, target, *extra)
    detail = ""
    ok = rc == want_rc
    if ok and substr is not None:
        blob = json.dumps(payload, ensure_ascii=False)
        ok = substr in blob
        detail = f"（未在输出里找到 {substr!r}）" if not ok else ""
    if ok:
        print(f"ok  {name}")
        PASS += 1
    else:
        print(f"FAIL {name}: rc={rc} want={want_rc} {detail}")
        print(f"     payload={json.dumps(payload, ensure_ascii=False)[:400]}")
        FAIL += 1
    return payload


def write(p: Path, text: str) -> Path:
    p.write_text(text, encoding="utf-8")
    return p


# --------------------------------------------------------------------- fixtures

TIMELINE_HDR = ("asset_id\tevent_id\tsource_range\tclip_range\tfinal_range\t"
                "speed/freeze\tnarration_text\taudio_duration_s\tsubtitle_source\n")

READY_SHEET = """# review sheet (synthetic, generated by the test)

```
成片文件        ：{final}
成片时长        ：{dur}            项目预期/容差：{tol}
源素材 asset_id ：rec-test            sha256：{sha}
剪辑完成时间    ：2026-01-01
审查人/模型     ：offline test
```

## A. 文件与时间线

| # | 检查项 | 结果 | 证据 |
|---|---|---|---|
| A1 | playable | 是 | ffprobe: 1 video + 1 audio |
| A2 | duration within tolerance | 是 | ffprobe format=duration |
| A3 | audio track present | 是 | ffprobe: aac 48kHz |
| A4 | time mapping self-consistent | 是 | timeline checker exit 0 |
| A5 | no **非预期** freeze | 是 | 12/12 sampled frames distinct |

## B. 单元覆盖

| 单元 | 出现？ | 事件数 | 源时间(s) | 成片时间(s) |
|---|---|---|---|---|
| 选牌 | 是 | 1 | 0.0-2.0 | 0.0-2.0 |

## C. 每单元五要素

```
理由(stated_reason)      ："sample"
事后复盘(retrospective_commentary) ：
```

## D. 关键结论回源核验

| 结论 | 模型候选值 | 源帧/游戏状态实测 | 一致？ |
|---|---|---|---|
| 胜负 | win | win | 是 |

- 尾段结局画面已强制覆盖（素材最后 10%）：是 → 结论：win

### D2. 问题清单

| issue_id | event_id | asset_id | 源区间 | 成片区间 | 旁白主张 | 实际画面 | 证据 | 局部修正建议 |
|---|---|---|---|---|---|---|---|---|

## E. 解说与字幕

| # | 检查项 | 结果 | 证据 |
|---|---|---|---|
| E1 | intro | 是 | 00:00.2 |
| E2 | pauses | 是 | 6 pauses >= 0.35s |
| E3 | measured durations | 是 | per-segment ffprobe |
| E4 | subs match audio | 是 | 1/1 identical |
| E5 | subs disappear | 是 | last cue ends early |
| E6 | subs from script | 是 | subtitle_source set |
| E7 | pronunciation checked on the real track | 是 | full-track listen |
| E8 | no narration/frame contradiction | 是 | mapped to source timecodes |
| E9 | no leftover direction text | 是 | full-track listen |

## F. 音画错配判定

| 上报的 mismatch | 判定 |
|---|---|
| none | 误报 |

- 误报数：{fp}  漏报数：{fn}
- 没有真值可比对时填 `unknown`，不要臆造 0。

## G. 安全与边界

| # | 检查项 | 结果 |
|---|---|---|
| G1 | no secrets | 是 |
| G2 | dual-window declared | N/A |
| G3 | no model output into decisions | 是 |

## H. 审查结论

通过
是否需要重做整场：否
"""


AUDIT_HDR = ("asset_id\tevent_id\tsource_range\tclip_range\tfinal_range\tspeed/freeze\t"
             "narration_text\taudio_duration_s\tsubtitle_source\tevent_phase\tclaim_phase\t"
             "anchor_asset\tanchor_event\tanchor_source\tevidence\thold_mark\tvisible_window\t"
             "subtitle_sha256\taudio_sha256\tfinal_sha256\n")


def sha256_file(path: Path) -> str:
    import hashlib
    return hashlib.sha256(path.read_bytes()).hexdigest()


def make_audit_inputs(root: Path, media: Path, dur: float) -> list:
    """采用时间线的审计输入（timeline + preflight + 静默台账 + 字幕 + 音轨 + 成片）。

    ready 门槛现在强制要求它们，而且**不接受**一份现成的审计 JSON 替代现场重跑，
    所以每个 ready 用例都要带上真实的一套；这里让时间线与 MP4 本身同长，
    保证正的用例真的能过、负的用例失败在它该失败的那一项上。
    """
    srt = write(root / "subs.srt", "1\n00:00:00,500 --> 00:00:01,500\nsynthetic line\n")
    tl = write(root / "timeline.tsv", AUDIT_HDR + "\t".join([
        "rec-test", "ev-1", f"0.0-{dur}", f"0.0-{dur}", f"0.0-{dur}", "1x",
        "synthetic line", f"{dur - 0.5}", "subs-test", "battle", "battle",
        "rec-test", "ev-1", f"0.5-{dur - 0.5}",
        "src rec-test@1.0s synthetic battle screen", "-", "-",
        sha256_file(srt), sha256_file(media), sha256_file(media)]) + "\n")
    pre = root / "preflight.json"
    subprocess.run([sys.executable, str(AUDIT_SCRIPT), "preflight", "--json", "--out", str(pre),
                    f"rec-test={media}"], check=True, capture_output=True, text=True)
    ledger = write(root / "gaps.tsv", "gap_id\tfinal_range\tdisposition\treason\n")
    return ["--timeline", str(tl), "--preflight", str(pre), "--silence-ledger", str(ledger),
            "--subtitle", str(srt), "--audio", str(media)]


def make_mp4(path: Path, seconds: float, tone: int = 440) -> None:
    subprocess.run([
        "ffmpeg", "-nostdin", "-v", "error", "-y",
        "-f", "lavfi", "-i", f"testsrc=size=320x240:rate=30",
        "-f", "lavfi", "-i", f"sine=frequency={tone}:duration={seconds}",
        "-t", str(seconds), "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p",
        "-c:a", "aac", str(path)], check=True, capture_output=True)


def mp4_duration(path: Path) -> float:
    out = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
                          "-of", "default=nw=1:nk=1", str(path)],
                         capture_output=True, text=True, check=True).stdout.strip()
    return float(out)


# --------------------------------------------------------------------- cases

def test_examples_pass_structure() -> None:
    expect("examples/timeline.example.tsv passes structure", 0, "timeline",
           EXAMPLES / "timeline.example.tsv")
    expect("examples/units.example.tsv passes structure", 0, "units",
           EXAMPLES / "units.example.tsv")
    expect("examples/review-sheet.example.md passes structure", 0, "sheet",
           EXAMPLES / "review-sheet.example.md")


def test_timeline_negative(root: Path) -> None:
    # final length must equal clip/speed + freeze
    bad = write(root / "t_math.tsv", TIMELINE_HDR +
                "rec-1\tev-1\t0.0-2.0\t0.0-2.0\t0.0-9.9\t1x\tx\t1.0\tsrc\n")
    expect("timeline: wrong final arithmetic is rejected", 1, "timeline", bad, substr="final 长度")

    # clip must be as long as source
    bad2 = write(root / "t_clip.tsv", TIMELINE_HDR +
                 "rec-1\tev-1\t0.0-2.0\t0.0-9.0\t0.0-9.0\t1x\tx\t1.0\tsrc\n")
    expect("timeline: clip/source length mismatch is rejected", 1, "timeline", bad2, substr="clip 长度")

    # overlapping clip ranges for the same asset
    bad3 = write(root / "t_overlap.tsv", TIMELINE_HDR +
                 "rec-1\tev-1\t0.0-2.0\t0.0-2.0\t0.0-2.0\t1x\tx\t1.0\tsrc\n"
                 "rec-1\tev-2\t2.0-4.0\t1.0-3.0\t2.0-4.0\t1x\ty\t1.0\tsrc\n")
    expect("timeline: overlapping clip ranges are rejected", 1, "timeline", bad3, substr="重叠")

    # unknown speed
    bad4 = write(root / "t_speed.tsv", TIMELINE_HDR +
                 "rec-1\tev-1\t0.0-2.0\t0.0-2.0\t0.0-2.0\tfast\tx\t1.0\tsrc\n")
    expect("timeline: unparsable speed/freeze is rejected", 1, "timeline", bad4, substr="speed/freeze")

    # a missing required column
    bad5 = write(root / "t_cols.tsv", "asset_id\tevent_id\nrec-1\tev-1\n")
    expect("timeline: missing columns are rejected", 1, "timeline", bad5, substr="缺少必需列")


def test_units_negative(root: Path) -> None:
    hdr = "event_id\tsource_range\tstate\taction\tstated_reason\tretrospective_commentary\toutcome\tcoverage\n"
    # empty stated_reason must be written as null/未记录
    bad = write(root / "u_empty.tsv", hdr +
                "ev-1\t0.0-1.0\tstate\taction\t\t\toutcome\tok\n")
    expect("units: empty stated_reason is rejected", 1, "units", bad, substr="stated_reason 为空")

    # reason_source marked as hindsight => backfill
    bad2 = write(root / "u_backfill.tsv",
                 hdr.rstrip("\n") + "\treason_source\n" +
                 "ev-1\t0.0-1.0\tstate\taction\t\"said it\"\t\"really thought it\"\toutcome\tok\t事后复盘\n")
    expect("units: hindsight reason_source is flagged as backfill", 1, "units", bad2, substr="回填")

    # illegal coverage value
    bad3 = write(root / "u_cov.tsv", hdr +
                 "ev-1\t0.0-1.0\tstate\taction\tnull\tnull\toutcome\tmaybe\n")
    expect("units: illegal coverage value is rejected", 1, "units", bad3, substr="coverage")

    # coverage_gap warns but does not fail on its own
    ok = write(root / "u_gap.tsv", hdr +
               "ev-1\t0.0-1.0\tstate\taction\tnull\tnull\toutcome\tcoverage_gap\n")
    expect("units: coverage_gap warns without failing", 0, "units", ok, substr="coverage_gap")


def test_sheet_negative(root: Path) -> None:
    text = (EXAMPLES / "review-sheet.example.md").read_text(encoding="utf-8")
    bad = write(root / "s_missing.md", text.replace("## F.", "## F-missing."))
    expect("sheet: missing required section is rejected", 1, "sheet", bad, substr="缺少必需章节")

    bad2 = write(root / "s_nounknown.md", text.replace("unknown", "zero"))
    expect("sheet: missing `unknown` escape hatch is rejected", 1, "sheet", bad2, substr="unknown")


def test_ready_positive_and_negative(root: Path) -> None:
    final = root / "final.mp4"
    make_mp4(final, 5.0)
    dur = round(mp4_duration(final), 3)
    sha = "0" * 64
    audit = make_audit_inputs(root, final, dur)
    good = write(root / "ready-ok.md",
                 READY_SHEET.format(final=final, dur=dur, tol=0.5, sha=sha, fp=0, fn=0))
    expect("ready: complete sheet + probed MP4 + audited timeline passes", 0, "ready", good,
           "--final-mp4", str(final), *audit)

    # the audit is a required part of the gate, not an optional extra
    expect("ready: missing --timeline is not ready (the audit is not optional)", 1, "ready", good,
           "--final-mp4", str(final), substr="--timeline")
    expect("ready: missing --preflight is not ready", 1, "ready", good,
           "--final-mp4", str(final), *[a for a in audit if a != "--preflight" and a != audit[audit.index("--preflight") + 1]],
           substr="--preflight")

    # no --final-mp4 => unverified, AND the audit still runs (no early return may skip it)
    expect("ready: missing --final-mp4 is not ready, and the audit still ran (no early return)",
           1, "ready", good, *audit, substr="成片文件不存在")

    # a timeline whose narration claims a phase that has not happened yet => not ready
    bad_tl = root / "timeline-phase.tsv"
    bad_tl.write_text((root / "timeline.tsv").read_text(encoding="utf-8")
                      .replace("\tbattle\tbattle\t", "\tbattle\treward\t"), encoding="utf-8")
    swapped = list(audit)
    swapped[1] = str(bad_tl)
    expect("ready: a phase-mismatched timeline blocks readiness", 1, "ready", good,
           "--final-mp4", str(final), *swapped, substr="时间线审计")

    # an output that is not the one the timeline was bound to => not ready
    other = root / "other.mp4"
    make_mp4(other, 5.0, tone=441)          # same length, different content
    other_sheet = write(root / "ready-other.md",
                        READY_SHEET.format(final=other, dur=dur, tol=0.5, sha=sha, fp=0, fn=0))
    expect("ready: swapping in a different exported cut breaks the content binding", 1, "ready",
           other_sheet, "--final-mp4", str(other), *audit, substr="时间线审计")

    # a remaining placeholder blocks readiness
    ph = write(root / "ready-ph.md",
               READY_SHEET.format(final=final, dur=dur, tol=0.5, sha=sha, fp=0, fn=0)
               .replace("ffprobe: 1 video + 1 audio", "____"))
    expect("ready: leftover placeholder is not ready", 1, "ready", ph, "--final-mp4", str(final),
           *audit, substr="占位符")

    # unknown misreport counts mean unverified => not ready
    unk = write(root / "ready-unknown.md",
                READY_SHEET.format(final=final, dur=dur, tol=0.5, sha=sha, fp="unknown", fn=0))
    expect("ready: unknown misreport count is not ready", 1, "ready", unk,
           "--final-mp4", str(final), *audit, substr="unknown")

    # declared duration outside tolerance
    off = write(root / "ready-dur.md",
                READY_SHEET.format(final=final, dur=round(dur + 9.0, 3), tol=0.5, sha=sha, fp=0, fn=0))
    expect("ready: duration outside tolerance is not ready", 1, "ready", off,
           "--final-mp4", str(final), *audit, substr="超出容差")

    # declared file != probed file ("review A, verify B")
    mismatch = write(root / "ready-mismatch.md",
                     READY_SHEET.format(final=other, dur=dur, tol=0.5, sha=sha, fp=0, fn=0))
    expect("ready: declared file != probed file is not ready", 1, "ready", mismatch,
           "--final-mp4", str(final), *audit, substr="不是同一个文件")

    # an item answered with a double option is not a pass
    dbl = write(root / "ready-dbl.md",
                READY_SHEET.format(final=final, dur=dur, tol=0.5, sha=sha, fp=0, fn=0)
                .replace("| A1 | playable | 是 |", "| A1 | playable | 是 / 否 |"))
    expect("ready: double-option verdict is not a pass", 1, "ready", dbl,
           "--final-mp4", str(final), *audit, substr="A1")

    # illegal tolerance must be refused (exit 2 = usage/read error)
    expect("ready: negative --tol is a usage error", 2, "ready", good,
           "--final-mp4", str(final), "--tol", "-1", *audit)


def main() -> int:
    if not CHECKER.is_file():
        print(f"checker not found: {CHECKER}", file=sys.stderr)
        return 2
    if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
        print("ffmpeg/ffprobe not found: the `ready` cases cannot run", file=sys.stderr)
        return 2
    root = Path(tempfile.mkdtemp(prefix="ppcheck-test-"))
    try:
        test_examples_pass_structure()
        test_timeline_negative(root)
        test_units_negative(root)
        test_sheet_negative(root)
        test_ready_positive_and_negative(root)
    finally:
        shutil.rmtree(root, ignore_errors=True)
    print(f"\n{PASS} passed, {FAIL} failed")
    return 1 if FAIL else 0


if __name__ == "__main__":
    sys.exit(main())
